spring:
    jackson:
         property-naming-strategy: SNAKE_CASE
         default-property-inclusion: non_null
         deserialization:
             fail_on_unknown_properties: false
    jmx:
        enabled: true
    data:
        mongodb:
            uri: mongodb://andrey.justo:social_bot@localhost:27017/social_bot
server:
    port: 8083
    
wit:
    endpoint: https://api.wit.ai
   
endpoints:
    enabled: false

---

spring:
    profiles: prod
    data:
        mongodb:
            uri: "ENC(LMMP+qGS4Xhd3CaxCJJyZU+5TI5Mu5ID63hhun3s1qbnIWEOKybpVQCt+L7DYrc2YSFB/b0kWzo/ky+mM3GZkJlkbCjgi8ST4v3TrsENJ0storlblkGh5A==)" 
     
    