spring:
    jackson:
         property-naming-strategy: SNAKE_CASE
         default-property-inclusion: non_null
         deserialization:
             fail_on_unknown_properties: false
    freemaker:
        cache: false
        
    jmx:
        enabled: true
        
    rabbitmq:
        host: localhost
        cacheMode: CONNECTION
        virtual-host: admin
        username: admin
        password: admin
        
    data:
        mongodb:
            uri: "ENC(LMMP+qGS4Xhd3CaxCJJyZU+5TI5Mu5ID63hhun3s1qbnIWEOKybpVQCt+L7DYrc2YSFB/b0kWzo/ky+mM3GZkJlkbCjgi8ST4v3TrsENJ0storlblkGh5A==)"

    servlet:
        multipart:
            max-file-size: 50KB
            max-request-size: 50KB
            
cloudinary:
    name:
    api-key:
    api-secret:

jasypt:
    encryptor:
        password: enactive-social-bot

wit:
    endpoint: https://api.wit.ai   
        
microsoft:
    face:
        endpoint: "https://[location].api.cognitive.microsoft.com"
        version: "v1.0"
        token: test
    speech:
        auth:
            url: "https://api.cognitive.microsoft.com/sts/v1.0/issueToken"
            key:
        recognize:
            app-id:
            url: "https://speech.platform.bing.com"
    luis-key: "[key]"
    luis-url: "[url]"
    knowledge-url: "[url]"
    knowledge-key: "[key]"

endpoints:
    enabled: false

authentication:
    secret: secret

queue:
    message-deliver: deliver
    message-receiver: receiver

---

spring:
    profiles: prod
    rabbitmq:
        host: "ENC(pEp1X1O7cFDO2PwTH/B9ZOcH32Jy1VTysuai402KJswkQhMSjwrYRQ==)"
        username: "ENC(5Fmq+MhqfBSMAmnLceyRca8HQu+qZ0lA)"
        password: "ENC(JSQKhXfXhzWDrlZ3VNcTaJTr3LhNaSXCUyXir19epK5psB9hgWp5uylRyostqjgG)"
        virtual-host: "ENC(5Fmq+MhqfBSMAmnLceyRca8HQu+qZ0lA)"
    data:
        mongodb:
            uri: "ENC(LMMP+qGS4Xhd3CaxCJJyZU+5TI5Mu5ID63hhun3s1qbnIWEOKybpVQCt+L7DYrc2YSFB/b0kWzo/ky+mM3GZkJlkbCjgi8ST4v3TrsENJ0storlblkGh5A==)" 
            
authentication:
    secret: "ENC(601/Jumv85kffnWbR4VqDAWv5VFcC/lV)"
    
cloudinary:
    name:
    api-key:
    api-secret:
     
    