server:
    port: 8080
    
spring:
    jackson:
         property-naming-strategy: SNAKE_CASE
         default-property-inclusion: non_null
         deserialization:
             fail_on_unknown_properties: false
    freemaker:
        cache: false
    jmx:
        enabled: true
    activemq:
        broker-url: "stomp+nio://localhost:61616?trace=true&wireFormat=stomp&persistent=false&useJmx=false&useShutdownHook=true"
    data:
        mongodb:
            uri: mongodb://andrey.justo:social_bot@localhost:27017/social_bot 
 
authentication:
    secret: secret

---

spring:
    profiles: prod
    activemq:
        broker-url: "{cipher}AAAAB3NzaC1yc2EAAAADAQABAAACAQDi855NVZwrY+kpx/IkYFDoi8/SdpWpKrgB3jMBHknJVYHuW7O0YmBN3jgBii1U...                 AgBsMAimWu25qvNtMeWImnbRze6qXZxFWr7kKOe/EsTAe5JyySPl9cDKA6t5Wav/9Qr+QKY35FH1rqjgKVtP8ndQWOkH2THIZK4IXuz2GUcEGexqAqdk3YFO47r2br8WSWBzI1JfSO7QSNH8dMYFJA0w274qr4lSyz8qiD40uCLZIGXj4nRnbkRhZUcTZnlyj/Si1+36aAejMqnR2KwnvEmpEkO5xLMnV9hDgm3T/Q0HU+hiYiAx/WqSOfkjj6GQmKrWk74HU8ykFCv3VUD+PN5+J18tVNhw0U0pKkUQLIlFKjAcXDzh5vP/BXAMnd8RwnQvLyNp3dL4aTpnaKJvPs10QylUTi/puszSZrWKmaNm+TTGTLil84AjwUpbnTdh64MIN/XKHE6l4pyZX2cUxlWPDnEJxv0PZHJ1cMRU6sF/ddy2V+P4E7i5a56hEFzpEGgKm7J1lHKFw6Omn2/cWTs0hQtm4W2wkXMRiXIUCyrbFSCEtPq6koBrIXwgpog6t4+XEVtxP0CC/Ig29nPvO/PMAeg6ECtUpiUVyF2zNdORookxi4JoTKBxyfUV/yrUJS5xX/EtkIVjTRdukg4JX+VbIxpIogVJcDGuolDwmZdfNZ52nV/fQZCHduAuBI4SRjwPNBSiZ4/SCNBNqhIZ18LWo3ZUNg07WD9zc8xOSWWXw7jIXHnSMI04fNWK6qCmJ4A+4dcRnbge/gGkQ1cEQ35VuY1Oww+2xW0lLTtbFLBaQUvGpD577e+snimg+FadFEiRiAX9mXCOYqLmWFgerUkn8BTk3lj1JBd79p1ttGqE+sDU1/YRwESs+9E3mZcegdKoMzQ4AE1ZuN1LH46MGTuj"
    data:
        mongodb:
            uri: '{cipher}AAAAB3NzaC1yc2EAAAADAQABAAACAQDi855NVZwrY+kpx/IkYFDoi8/SdpWpKrgB3jMBHknJVYHuW7O0YmBN3jgBii1U...                 AgCH+J+ceeRtpVGd0OiU2vADmUEc5VVRIAlmS9OlwHAqvbNQgIAgOGqc5XKUqY+Cm1+mA5xLNexKfHXsx/Zo1gVGcd6oXbxHPvXhPPn5oEnKmugp/C+TTS335grFb8Ov9GQLosMCvHUvYWecyUjcrWgcASTiN2DMDnReiHL7bSFfOWhG2s+ZmLrpFJbZfUH7GoQwyT6yxB0q8PmDCQB1eGqruLKp2LSGZpoGF5Ja3trYuOnRpojiS/vxDg8/mti7lJqOIZaP9rbVIMDfok0COBgXy8a38TZ0CqLQNxOFVqMwq2tq8qMRoit+Ef/+NOn3xlDABWhEGSmfPzZQz1ofEm+egaBWzi1mWVpM21wS8eJ8U/wP1DqNWPMJ8qarl3luadDcXxnWX8f+TpOhuwM387K2BQoZEfnXWmA/sV+YF59cCiFRTUXHmmBYgZrU03EdwTbN1ciC3aRMjipPIZQ+dYe03AP18vEBN+CxwpM65IVQUdQHv0ZmxnhxU88KTW7k4Teu8MX3c7EoDn/MnMmTUnlzbD9tgu7U72F2RKfj37diaHsEwKuV8WkUg/S/dU7Q46xLFTWJdAUYW/Ujbt90h2bMQpppfzoHdc2mtt/zLpPowyVJLRyCAmyyWgBzKlvffQYU589y1Pu4GA94jp0i5LOAs46bLVGlfpvEVrinFIe6aCYbGav8bi7BB4XZtL8fcRHBvij8OvdYfwfphT29iW1mTb8ePLf0gdAAPxiN9rPYNH7kmMj6UrpKI6menyrSCtc2RrIiOQVjQbT3WLoYdP8s0nOBx0ANgWnAucon+DHwAP351a7pKjLysRm/JSbwFE0=' 
            
authentication:
    secret: '{cipher} AAAAB3NzaC1yc2EAAAADAQABAAACAQDi855NVZwrY+kpx/IkYFDoi8/SdpWpKrgB3jMBHknJVYHuW7O0YmBN3jgBii1U...                 AgAzL4YjbbJwcKQmkwVK8IrywRHSUHjdGXygU+5uk+EwIdfKXswxCTBIq+iObebV78XnwDIN49q1yaXfSdWWfdByQGhOlKJ7dtBkLshXy41/5HSA82AQNjDjyK97T65lbClO1KD61URcVy8fqJB/gZ+IuAYbMSWKejQoG9Wk3sO0tduN3nZ2EgB7wxLeDEFAYLzdVJEWOpgG7zDaBGCK5FkxaoIrlKgXaGSvbeUTumVnbdCZyrEq32BBZFLzrteCLH+zXxxu6hDA7KURJ7uJQzo7Q3Pju/Rof5+IRP2CEFSoAJ8Y1yCuiYRNA/7UXmmEKpv/5Xcz9PJ/mX0kO/R2lpmi1oZjsrlf8AFgDFIQocCieAgfAinxtPDgrQVTjNXVUoGjrN6tGB/XaKPOUF8qjBBrqjq1EyjpymCS4vh2W2uSbUKVii4biU3cJpdBEgY6UOwet4ivY9BOXFaJ0KAo/tFBa2dUMLOM5ewE1NAvZtyPrLM+GcLWBcx7u8yBN4ZExsL+oqt43fYBixCVRcjAVuXFiag0fDs0Fe5Kd2uIMHis+Glf62GbGlP02cMelfEMDnwLiOYPKHeYVTVAOetufrUFtYlokKwEdZscT3kmRsbhJZLDqdMTr1hfp88BK8D8esqoYF02fJ02r0CWl7yEqKNwMMws/4ejjUeGpkU1zOMbXTW7chqQB/4/Jec7duN/NaFfQF0aEjL3qVkHuyKpdpS4'